[package]
name = "sandbox_01"
version = "0.1.0"
authors = ["kz56cd <kz56cd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
